# Generated by Django 4.2.4 on 2023-09-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_post_liters_required_alter_post_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blood_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'A+'), (1, 'A-'), (2, 'B+'), (3, 'B-'), (4, 'AB+'), (5, 'AB-'), (6, 'O+'), (7, 'O-')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ImagenesPedidos/'),
        ),
    ]
