# Generated by Django 4.2.4 on 2023-09-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_bloodtype_alter_post_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liters_donated',
            field=models.FloatField(default=0),
        ),
    ]
