# Generated by Django 4.2.4 on 2023-10-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_alter_post_liters_donated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.IntegerField(default=0),
        ),
    ]
