# Generated by Django 4.2.4 on 2023-10-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_post_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='longitud',
            field=models.FloatField(default=0),
        ),
    ]
